spring:
  redis:
    host: 192.168.239.128
    port: 6379
#    client-type: jedis
#    client-type: lettuce
    password: 123456 #密码

#    redis连接池配置
#    jedis:
#      pool:
#        max-active: 8 #最大连接数
#        max-wait: 1ms  #连接池的最大阻塞等待时间
#        max-idle: 4  #连接池的最大空闲连接
#        min-idle: 0 #连接池的最小空闲连接

