spring:
  mail:
#    \u4F9B\u5E94\u5546SMTP\u534F\u8BAE
    host: smtp.qq.com
#    \u53D1\u9001\u65B9
    username: 3490596334@qq.com
    password: ohyepvqjhpzedbci
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true