spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webframe?serverTimezone=UTC
    username: root
    password: yswysyydxj

#mp\u8BBE\u7F6Eid\u81EA\u589E
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: tbl_

  #\u914D\u7F6E\u65E5\u5FD7\u63A7\u5236\u53F0\u8F93\u51FA
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  port: 8080
